services:
  alloy:
    image: grafana/alloy:latest@sha256:85e4a706181741dd735d9a69bea81f9e03e16d5349bff46dd9640379f143c007
    container_name: alloy
    environment:
      TZ: ${TZ}
    volumes:
      - type: bind
        source: ${docker_volume_path}/grafana/config.alloy
        target: /etc/alloy/config.alloy
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /:/hostfs:ro
      - /proc:/hostfs/proc:ro
      - /dev:/hostfs/dev:ro
      - /mnt:/hostfs/mnt:ro
    ports:
      - "12441:12441"
    command: >
      run --server.http.listen-addr=0.0.0.0:12441 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
