services:
  cloudflared:
    image: cloudflare/cloudflared:latest@sha256:5bb6a0870686742d00e171f36c892ba91e5994631bc363d808b9ba822262dad6
    network_mode: "host"
    container_name: cloudflared_tunnel
    command: tunnel run --token ${cloudflare_tunnel_token}
    environment:
      TZ: ${TZ}
