services:
  cloudflared:
    image: cloudflare/cloudflared:latest@sha256:404528c1cd63c3eb882c257ae524919e4376115e6fe57befca8d603656a91a4c
    network_mode: "host"
    container_name: cloudflared_tunnel
    command: tunnel run --token ${cloudflare_tunnel_token}
    environment:
      TZ: ${TZ}
