services:
  cloudflared:
    image: cloudflare/cloudflared:latest@sha256:89ee50efb1e9cb2ae30281a8a404fed95eb8f02f0a972617526f8c5b417acae2
    network_mode: "host"
    container_name: cloudflared_tunnel
    command: tunnel run --token ${cloudflare_tunnel_token}
    environment:
      TZ: ${TZ}
