services:

  db:
    image: library/mariadb:latest@sha256:f54db0cb3ccfe9431aba6d08c65a1763c499789b116b4cb651dd7fcf325965b3
    restart: always
    networks:
      - mariadb
    container_name: mariadb
    ports:
      - 3312:3306
    labels:
      - traefik.enable=true
      - traefik.http.routers.mariadb.rule=Host(`mariadb.${public_domain_name}`) || Host(`mariadb.${local_domain_name}`)
      - traefik.http.routers.mariadb.entrypoints=web
      - traefik.http.services.mariadb.loadbalancer.server.port=3306
    volumes:
      - ${docker_volume_path}/mariadb:/var/lib/mysql
    environment:
      MARIADB_USER: ${mariadb_user}
      MARIADB_PASSWORD: ${mariadb_password}
      MARIADB_ROOT_PASSWORD: ${mariadb_root_password}
      MARIADB_AUTO_UPGRADE: ${mariadb_auto_upgrade}

  adminer:
    image: library/adminer:latest@sha256:a3167350c4eb9ae4473b8ea0f49c8e5ae74c87b240ee2f6086521dba2a6bf243
    networks:
      - mariadb
    restart: always
    ports:
      - 8306:8080
    labels:
    - traefik.enable=true
    - traefik.http.routers.mariaadmin.rule=Host(`mariaadmin.${public_domain_name}`) || Host(`mariaadmin.${local_domain_name}`)
    - traefik.http.routers.mariaadmin.entrypoints=web
    - traefik.http.services.mariaadmin.loadbalancer.server.port=8080

networks:
  mariadb:
    driver: bridge
