services:

  db:
    image: library/mariadb:latest@sha256:b1cb255a9939d28a1856815f0de6046c20c28c21b92a9f2696bc782b247a47ee
    restart: always
    networks:
      - mariadb
    container_name: mariadb
    ports:
      - 3312:3306
    labels:
      - traefik.enable=true
      - traefik.http.routers.mariadb.rule=Host(`mariadb.${public_domain_name}`) || Host(`mariadb.${local_domain_name}`)
      - traefik.http.routers.mariadb.entrypoints=web
      - traefik.http.services.mariadb.loadbalancer.server.port=3306
    volumes:
      - ${docker_volume_path}/mariadb:/var/lib/mysql
    environment:
      MARIADB_USER: ${mariadb_user}
      MARIADB_PASSWORD: ${mariadb_password}
      MARIADB_ROOT_PASSWORD: ${mariadb_root_password}
      MARIADB_AUTO_UPGRADE: ${mariadb_auto_upgrade}

  adminer:
    image: library/adminer:latest@sha256:2fb88b98da9f0ae0157d8fcb73f447a0747b09ee8d2ff8a8e0695b30afed2116
    networks:
      - mariadb
    restart: always
    ports:
      - 8306:8080
    labels:
    - traefik.enable=true
    - traefik.http.routers.mariaadmin.rule=Host(`mariaadmin.${public_domain_name}`) || Host(`mariaadmin.${local_domain_name}`)
    - traefik.http.routers.mariaadmin.entrypoints=web
    - traefik.http.services.mariaadmin.loadbalancer.server.port=8080

networks:
  mariadb:
    driver: bridge
